### ISSUE TITLE
I'm having trouble with the installation

### ISSUE THREAD

**Issue by fkay9** [Vedant-Bhalgama/VySecator#4]
When installing python2.7.14. I got python 2.7.14 (64-bit) setup ended prematurely because an error. Your system has not be modified. To install the program at a later time. Please run install again. 
This was when I ran setup.py

**Comment by Vedant-Bhalgama** [comment]
Hi!
Can you send me a screenshot of the error? So i can understand it.

**Comment by Vedant-Bhalgama** [comment]
Try to run the setup.py again, It will work, If you get the error again, Please send me a screenshot of it!

**Comment by fkay9** [comment]
I will send the screenshot

**Comment by fkay9** [comment]
![Screenshot_2020-09-01_18-08-19](https://user-images.githubusercontent.com/64831981/91923996-b04ccd80-ec9f-11ea-956a-bc3a2c4994ee.png)

**Comment by Vedant-Bhalgama** [comment]
Download a Python 2.7.14 MSI File from here https://www.python.org/ftp/python/2.7.14/python-2.7.14.amd64.msi

After it gets downloaded use this command to install it 

`wine msiexec /i python-2.7.14.amd64.msi`

Try this and see if you get errors.

**Comment by fkay9** [comment]
Okay thanks I will check it out

**Comment by fkay9** [comment]
![Screenshot_2020-09-02_16-23-01](https://user-images.githubusercontent.com/64831981/92050068-1e55cb00-ed5a-11ea-82a7-47dffc71e59e.png)

**Comment by Vedant-Bhalgama** [comment]
I don't know why you are getting this error, What you can do is, Uninstall the wine from your Kali Linux and then I will give you a list of commands to run, try installing wine from that.

First, Remove the previous version of your wine or the current one which you are having

Then run this commands

`apt update`
`apt install -y aptitude`
`aptitude install wine`
`aptitude install wine32`

**Comment by Vedant-Bhalgama** [comment]
Hi! 

Please tell me if it worked or not, I need to close this issue after 24 Hours!

**Comment by fkay9** [comment]
Okay I will try it now

**Comment by fkay9** [comment]
I tried it and I am getting the same thing. Since you said you will close it in 24 hours do you have an email in case you find a solution

**Comment by Vedant-Bhalgama** [comment]
Uhh, i dont know why it still didn't work, Because a same guy same guy came with this error and I told the same steps which worked for him .... Try any another python2 version, Download Python 2.7.15.msi and run it with wine

**Comment by fkay9** [comment]
Okay I will try that

**Comment by fkay9** [comment]
I got the same thing I typed wine msiexec /i python-2.7.14.amd64.msi

**Comment by fkay9** [comment]
Wait nevermind it works the installation for python2.7 I had to type wine64

**Comment by fkay9** [comment]
Now I will see if installing the tool works

**Comment by fkay9** [comment]
But running the tool gets the same error. To run the tool setup I typed python3 setup.py

**Comment by Vedant-Bhalgama** [comment]
Nice! Now try it

**Comment by Vedant-Bhalgama** [comment]
Don't try with python3 try with python2 only, python ./setup.py

**Comment by fkay9** [comment]
![Screenshot_2020-09-05_17-02-28](https://user-images.githubusercontent.com/64831981/92315947-39734580-efbb-11ea-8fd2-446da0b4cc2a.png)

**Comment by fkay9** [comment]
I am not sure why it does not work with python2

**Comment by Vedant-Bhalgama** [comment]
run this command `pip install colorama` `pip install pyfiglet` then run the setup.py file

**Comment by fkay9** [comment]
I will do that

**Comment by fkay9** [comment]
Tell you how it goes

**Comment by fkay9** [comment]
So I done that which solved the python2 problem but I still got the "ended prematurely error". It's okay if nothing can be done at the moment. I am very thankful that you tried to help me

**Comment by Vedant-Bhalgama** [comment]
Sorry to hear it ..... What can be done is try installing Kali again.

**Comment by Vedant-Bhalgama** [comment]
So now I am closing the issue, If you have any doubts regarding to it, Please feel free to open a new one.

Thanks and Regards,
Vedant
