### ISSUE TITLE
Update on my last issues

### ISSUE THREAD

**Issue by fkay9** [Vedant-Bhalgama/VySecator#5]
I'm not sure if this helps but after I got "python ended prematurely error". I noticed this
![Screenshot_2020-09-05_22-08-32](https://user-images.githubusercontent.com/64831981/92319432-101bdf00-efe6-11ea-996e-e5b4c2eb42fd.png)

**Comment by Vedant-Bhalgama** [comment]
This came because of the Python Setup which you ran got error.

**Comment by krishpranav** [comment]
Hi fkay9
i got this error while installing veil and then i gave full access to every folder as executable
so that any tool can create a folder in your root directory
ex:
cd /
sudo chmod 777 etc
cd etc
sudo chmod 777 proxychains.conf
like this

**Comment by Vedant-Bhalgama** [comment]
What? This is not the repository of Veil... What are you talking about? Better be sure where you post!

**Comment by Vedant-Bhalgama** [comment]
Sorry for the false alarms,

Yes fkay9 better try this

**Comment by Vedant-Bhalgama** [comment]
Please feel free to open a new issue and tell me how it goes!
