### ISSUE TITLE
Doubt in the code

### ISSUE THREAD

**Issue by riddhiman1** [Vedant-Bhalgama/VySecator#7]
In line number 57 the code is:
`subprocess.call(['wine', '/root/.wine/drive_c/Python27/Scripts/pyinstaller', '--onefile', '--noconsole', '--icon', ask_icon_path, ask_path])`
Should it be :
`subprocess.call(['wine', '/root/.wine/drive_c/Python27/Scripts/pyinstaller.exe', '--onefile', '--noconsole', '--icon', ask_icon_path, ask_path])`

**Comment by Vedant-Bhalgama** [comment]
Yes indeed, I am working on the Python3 Version of the code, It soon will be released. Thank You for reporting!
