### ISSUE TITLE
Hay 2 errores 

### ISSUE THREAD

**Issue by ghost** [Vedant-Bhalgama/VySecator#8]
Error 1 : En la línea 55 módulo setup()

Error 2 : Línea 27 'raw_input' no está definido

Nota: El script se ejecuta, aparece el banner pero cuando dice que espere un momento hay sale el error. Espero y lo pueda solucionar ya que estaba en busca de una herramienta para ofuscar un archivo y está fue la única que encontré y me pareció muy buena pero lástima que sale ese error.

**Comment by Vedant-Bhalgama** [comment]
I know it's been a long since this message but, I was a noob programmer back then, I had just got into IT stuff and programming so you know, But this script is made for Python 2. Not for 3. I'll be mostly updating this to Python 3 soon.
